name = "OBOParse"
uuid = "afb48802-0cf5-5a61-b18d-a3da2e9c5fb6"
authors = ["Maxim Grechkin"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
